const $=s=>document.querySelector(s);let state={media:[],libs:[],system:null,user:null};
async function api(path,opt={}){const r=await fetch(path,{headers:{'Content-Type':'application/json',...(opt.headers||{})},...opt});if(r.status===401){loginView();throw new Error('unauthorized')}const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Fehler');return j}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function toast(t){let x=document.createElement('div');x.className='toast';x.textContent=t;document.body.append(x);setTimeout(()=>x.remove(),2500)}
function loginView(){document.querySelector('#app').innerHTML=`<div class="login"><form class="login-card" id="login"><div class="brand"><span class="mark">▶</span> BuddyFlix</div><h1>Willkommen zurück.</h1><div class="muted">Dein schlanker Media Server.</div><label class="field">Benutzer<input name="u" value="admin" autocomplete="username"></label><label class="field">Passwort<input name="p" type="password" autocomplete="current-password"></label><button class="btn primary">Anmelden</button><div id="err" class="muted" style="margin-top:14px"></div></form></div>`;$('#login').onsubmit=async e=>{e.preventDefault();try{await api('/api/login',{method:'POST',body:JSON.stringify({Username:e.target.u.value,Password:e.target.p.value})});await boot()}catch(x){$('#err').textContent=x.message}}}
function shell(){document.querySelector('#app').innerHTML=`<div class="shell"><aside class="side"><div class="brand"><span class="mark">▶</span> BuddyFlix</div><nav class="nav"><button data-v="home" class="active">⌂ Startseite</button><button data-v="movies">▣ Filme</button><button data-v="admin">⚙ Verwaltung</button></nav><div class="sidefoot">BuddyFlix v0.1.0<br>ARMHF-first Media Server</div></aside><main class="main"><header class="top"><input id="search" class="search" placeholder="Filme durchsuchen…"><span class="status"><i class="dot"></i> Server online</span><button class="btn ghost" id="logout">Abmelden</button></header><div id="content" class="content"></div></main></div>`;document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>view(b.dataset.v,b));$('#logout').onclick=async()=>{await api('/api/logout',{method:'POST'});loginView()};let timer;$('#search').oninput=e=>{clearTimeout(timer);timer=setTimeout(async()=>{state.media=await api('/api/media?q='+encodeURIComponent(e.target.value));renderMovies()},180)}}
async function boot(){try{state.system=await api('/api/system');state.media=await api('/api/media');state.libs=await api('/api/libraries');shell();renderHome()}catch(e){if(e.message!=='unauthorized')loginView()}}
function view(v,b){document.querySelectorAll('.nav button').forEach(x=>x.classList.toggle('active',x===b));if(v==='home')renderHome();if(v==='movies')renderMovies();if(v==='admin')renderAdmin()}
function card(m){return `<article class="card" onclick="detail(${m.id})"><div class="poster">${m.poster?`<img loading="lazy" src="${esc(m.poster)}">`:`<div class="placeholder">▶</div>`}${m.progress>0&&m.progress<95?`<div class="progress"><i style="width:${Math.min(100,m.progress)}%"></i></div>`:''}</div><div class="card-title">${esc(m.title)}</div><div class="card-meta">${m.year||'Film'}${m.progress>=95?' · ✓ gesehen':''}</div></article>`}
function renderHome(){let cont=state.media.filter(m=>m.progress>1&&m.progress<95).slice(0,8),hero=state.media.find(m=>m.backdrop)||state.media[0];$('#content').innerHTML=`${hero?`<section class="hero"><div class="hero-bg" style="background-image:url('${esc(hero.backdrop||hero.poster||'')}')"></div><div class="hero-copy"><div class="muted">BUDDYFLIX EMPFIEHLT</div><h1>${esc(hero.title)}</h1><p>${esc(hero.overview||'Deine Medienbibliothek auf dem QNAP – direkt, schnell und ohne Ballast.')}</p><button class="btn primary" onclick="play(${hero.id})">▶ Abspielen</button></div></section>`:''}${cont.length?`<div class="rowhead"><h2>Weiterschauen</h2></div><div class="grid">${cont.map(card).join('')}</div>`:''}<div class="rowhead"><h2>Neu hinzugefügt</h2><span class="muted">${state.media.length} Titel</span></div><div class="grid">${state.media.slice(0,18).map(card).join('')||'<div class="muted">Noch keine Medien. Lege unter Verwaltung eine Bibliothek an.</div>'}</div>`}
function renderMovies(){if(!$('#content'))return;$('#content').innerHTML=`<div class="rowhead"><h2>Filme</h2><span class="muted">${state.media.length} Titel</span></div><div class="grid">${state.media.map(card).join('')||'<div class="muted">Keine Treffer.</div>'}</div>`}
async function renderAdmin(){state.system=await api('/api/system');state.libs=await api('/api/libraries');let s=state.system;$('#content').innerHTML=`<div class="rowhead"><h2>Verwaltung</h2><div class="toolbar"><button class="btn primary" id="scan">Bibliotheken scannen</button></div></div><div class="stats"><div class="stat"><b>${s.media}</b><span>Medien</span></div><div class="stat"><b>${s.libraries}</b><span>Bibliotheken</span></div><div class="stat"><b>${s.cpus}</b><span>CPU Threads</span></div><div class="stat"><b>${s.memory_mb} MB</b><span>BuddyFlix RAM</span></div></div><div class="split" style="margin-top:18px"><section class="panel"><h3>Bibliotheken</h3><table class="table"><thead><tr><th>Name</th><th>Pfad</th><th></th></tr></thead><tbody>${state.libs.map(l=>`<tr><td>${esc(l.name)}</td><td class="muted">${esc(l.path)}</td><td><button class="btn danger" onclick="removeLib(${l.id})">×</button></td></tr>`).join('')}</tbody></table><form id="libform"><label class="field">Name<input name="name" placeholder="Filme"></label><label class="field">QNAP-Pfad<input name="path" placeholder="/share/Multimedia/Filme"></label><button class="btn primary">Bibliothek hinzufügen</button></form></section><section class="panel"><h3>System</h3><table class="table"><tr><td>Version</td><td>${s.version}</td></tr><tr><td>Plattform</td><td>${s.os}/${s.arch}</td></tr><tr><td>Go</td><td>${s.go}</td></tr><tr><td>Uptime</td><td>${Math.floor(s.uptime_sec/60)} min</td></tr><tr><td>TMDb</td><td>${s.tmdb?'aktiv':'nicht konfiguriert'}</td></tr><tr><td>Scanner</td><td>${s.scanning?'läuft':'bereit'}</td></tr></table><p class="muted">TMDb optional über die Umgebungsvariable <code>TMDB_API_KEY</code>.</p></section></div>`;$('#scan').onclick=doScan;$('#libform').onsubmit=addLib}
async function addLib(e){e.preventDefault();try{await api('/api/libraries',{method:'POST',body:JSON.stringify({name:e.target.name.value,path:e.target.path.value,type:'movies'})});toast('Bibliothek hinzugefügt');renderAdmin()}catch(x){toast(x.message)}}
async function removeLib(id){if(!confirm('Bibliothek und Index entfernen? Die Mediendateien bleiben unangetastet.'))return;await api('/api/libraries?id='+id,{method:'DELETE'});await refresh();renderAdmin()}
async function doScan(){let b=$('#scan');b.disabled=true;b.textContent='Scan läuft…';try{let r=await api('/api/scan',{method:'POST'});toast(`${r.files_seen} Dateien gefunden`);await refresh();renderAdmin()}catch(x){toast(x.message)}finally{b.disabled=false}}
async function refresh(){state.media=await api('/api/media');state.libs=await api('/api/libraries');state.system=await api('/api/system')}
async function detail(id){let a=await api('/api/media?id='+id),m=a[0];if(!m)return;let el=document.createElement('div');el.className='modal';el.innerHTML=`<div class="modalbox"><div class="moviehero" style="background-image:url('${esc(m.backdrop||m.poster||'')}')"><button class="close">×</button><div class="moviecopy"><div class="muted">${m.year||''}</div><h1>${esc(m.title)}</h1><p>${esc(m.overview||'Für diesen Titel wurden noch keine Metadaten geladen.')}</p><div class="modalactions"><button class="btn primary" id="p">▶ Abspielen</button><button class="btn ghost" id="meta">Metadaten laden</button></div></div></div></div>`;document.body.append(el);el.querySelector('.close').onclick=()=>el.remove();el.onclick=e=>{if(e.target===el)el.remove()};el.querySelector('#p').onclick=()=>{el.remove();play(id)};el.querySelector('#meta').onclick=async()=>{try{await api('/api/metadata/'+id,{method:'POST'});toast('Metadaten aktualisiert');el.remove();await refresh();renderHome()}catch(x){toast(x.message)}}}
async function play(id){let a=await api('/api/media?id='+id),m=a[0];if(!m)return;let el=document.createElement('div');el.className='videoModal';el.innerHTML=`<video controls autoplay src="/stream/${id}"></video><button class="close">×</button>`;document.body.append(el);let v=el.querySelector('video'),last=0;v.onloadedmetadata=()=>{if(m.position>0&&m.duration>0&&m.position<m.duration-20)v.currentTime=m.position};v.ontimeupdate=()=>{if(Date.now()-last>10000){last=Date.now();saveProgress(id,v.currentTime,v.duration)}};v.onended=()=>saveProgress(id,v.duration,v.duration);el.querySelector('.close').onclick=()=>{saveProgress(id,v.currentTime,v.duration);v.pause();el.remove();refresh()}}
async function saveProgress(id,p,d){if(!Number.isFinite(d)||d<=0)return;try{await api('/api/progress',{method:'POST',body:JSON.stringify({media_id:id,Position:p,Duration:d})})}catch{}}
boot();
